### PR TITLE
feat: support for customized methods through option

### PR DESCRIPTION
**Pull request by wulorn**
- [] Do only one thing
- [] Non breaking API changes
- [] Tested

### What did this pull request do?
`Support DIY method`

### User Case Description

```
gen.WithDIYMethod(WithTableNameMethod(uint64(shardNumber)))

var WithTableNameMethod = func(shardNumber uint64) *gen.Method {
	buf := bytes.NewBufferString(fmt.Sprintf("{\n\tconst shardNumber = %d", shardNumber))
	buf.WriteString("\n\treturn \"@@table\" + fmt.Sprintf(\"_%d\", shardId % shardNumber)\n}")
	body := buf.String()
	return &gen.Method{
		Receiver: gen.Param{
			Type:      "defaultModel",
			IsPointer: true,
		},
		MethodName: "TableName",
		Params: []gen.Param{
			{
				Name: "shardId",
				Type: "uint64",
			},
		},
		Result: []gen.Param{
			{
				Type: "string",
			},
		},
		Body: body,
	}
}
```

### CODE REVIEW

**Comment by qqxhb** [comment]
@wulorn [DIY-TableName](https://gorm.io/gen/database_to_structs.html#DIY-TableName)

**Comment by wulorn** [comment]
> @wulorn [DIY-TableName](https://gorm.io/gen/database_to_structs.html#DIY-TableName)

DIY-TableName cannot customize a function body

**Comment by qqxhb** [comment]
> 

Can be customized. It's just that the input parameter is fixed.
`TableName()` or `TableName(namer schema.Namer) `
This method is only executed once during initialization.

The example you gave belongs to a [dynamic table name](https://gorm.io/docs/conventions.html#Temporarily-specify-a-name), you need to manually call it every time.
e.g.
```go
    user := &model.User{xxx}
    u := query.User.Table(user.TableName(1))
    u.WithContext(ctx).Create(user)
```

**Comment by wulorn** [comment]
> > 
> 
> Can be customized. It's just that the input parameter is fixed. `TableName()` or `TableName(namer schema.Namer) ` This method is only executed once during initialization.
> 
> The example you gave belongs to a [dynamic table name](https://gorm.io/docs/conventions.html#Temporarily-specify-a-name), you need to manually call it every time. e.g.
> 
> ```go
>     user := &model.User{xxx}
>     u := query.User.Table(user.TableName(1))
>     u.WithContext(ctx).Create(user)
> ```

**Comment by qqxhb** [comment]
e.g.

1. Define template method

```go
func (m *CommonMethod) TableName(ID int64) string {
	shard := 10
	return fmt.Sprintf("@@table%d", ID%shard)
}
```
or
```go
func (m *CommonMethod) ShardTableName() string {
	shard := 10
	return "@@table" + fmt.Sprintf("%d", m.ID%shard)
}
```

2.  Generate code with option
`gen.WithMethod(method.CommonMethod{}.TableName)`
3.  use diy table name
   ``` go
 user := &model.User{xxx}
    u := query.User.Table(user.TableName(1))
    u.WithContext(ctx).Create(user)
```

**Comment by wulorn** [comment]
> e.g.
> 
> 1. Define template method
> 
> ```go
> func (m *CommonMethod) TableName(ID int64) string {
> 	shard := 10
> 	return fmt.Sprintf("@@table%d", ID%shard)
> }
> ```
> 
> or
> 
> ```go
> func (m *CommonMethod) ShardTableName() string {
> 	shard := 10
> 	return "@@table" + fmt.Sprintf("%d", m.ID%shard)
> }
> ```
> 
> 2. Generate code with option
>    `gen.WithMethod(method.CommonMethod{}.TableName)`
> 3. use diy table name
> 
> ```go
> user := &model.User{xxx}
>  u := query.User.Table(user.TableName(1))
>  u.WithContext(ctx).Create(user)
> ```

--- 
We use custom `gentool` to generate DB models by reading fields from the database, not through the structure

e.g.

1. diy table name

```go
var WithTableNameMethod = func(shardNumber uint64) *gen.Method {
	buf := bytes.NewBufferString(fmt.Sprintf("{\n\tconst shardNumber = %d", shardNumber))
	buf.WriteString("\n\treturn \"@@table\" + fmt.Sprintf(\"_%d\", shardId % shardNumber)\n}")
	body := buf.String()
	return &gen.Method{
		Receiver: gen.Param{
			Type:      "defaultModel",
			IsPointer: true,
		},
		MethodName: "TableName",
		Params: []gen.Param{
			{
				Name: "shardId",
				Type: "uint64",
			},
		},
		Result: []gen.Param{
			{
				Type: "string",
			},
		},
		Body: body,
	}
}

```
2. use custom `gentool` generate model, the `shardNumber` is a variable.

```go
gen.WithDIYMethod(WithTableNameMethod(shardNumber))
```

**Comment by wulorn** [comment]
> e.g.
> 
> 1. Define template method
> 
> ```go
> func (m *CommonMethod) TableName(ID int64) string {
> 	shard := 10
> 	return fmt.Sprintf("@@table%d", ID%shard)
> }
> ```
> 
> or
> 
> ```go
> func (m *CommonMethod) ShardTableName() string {
> 	shard := 10
> 	return "@@table" + fmt.Sprintf("%d", m.ID%shard)
> }
> ```
> 
> 2. Generate code with option
>    `gen.WithMethod(method.CommonMethod{}.TableName)`
> 3. use diy table name
> 
> ```go
> user := &model.User{xxx}
>  u := query.User.Table(user.TableName(1))
>  u.WithContext(ctx).Create(user)
> ```

--- 
We use custom `gentool` to generate DB models by reading fields from the database, not through the structure

e.g.

1. diy table name

```go
var WithTableNameMethod = func(shardNumber uint64) *gen.Method {
	buf := bytes.NewBufferString(fmt.Sprintf("{\n\tconst shardNumber = %d", shardNumber))
	buf.WriteString("\n\treturn \"@@table\" + fmt.Sprintf(\"_%d\", shardId % shardNumber)\n}")
	body := buf.String()
	return &gen.Method{
		Receiver: gen.Param{
			Type:      "defaultModel",
			IsPointer: true,
		},
		MethodName: "TableName",
		Params: []gen.Param{
			{
				Name: "shardId",
				Type: "uint64",
			},
		},
		Result: []gen.Param{
			{
				Type: "string",
			},
		},
		Body: body,
	}
}

```
2. use custom `gentool` generate model, the `shardNumber` is a variable.

```go
gen.WithDIYMethod(WithTableNameMethod(shardNumber))
```

**Comment by qqxhb** [comment]
`gen.WithMethod` [Methods-Template](https://gorm.io/gen/database_to_structs.html#Methods-Template)
This option is only effective when generated from DB.

**Comment by wulorn** [comment]
> `gen.WithMethod` [Methods-Template](https://gorm.io/gen/database_to_structs.html#Methods-Template) This option is only effective when generated from DB.

yes, the `gen.WithDIYMethod` option is also the same as `gen.WithMethod`,  but it can make diy methods easier, especially when using custom tools. hope to be merged

**Comment by jinzhu** [comment]
Hi @wulorn 

Thank you for your PR, we would like to have the compiler check for the configuration, so don't really want to use the text template.

**Pull request closed without merging**
