### PR TITLE
feat: support table comment

### PR DESCRIPTION
**Pull request by maiqingqiang**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

support table comment. #673 
1. [https://github.com/go-gorm/gorm/pull/6225](https://github.com/go-gorm/gorm/pull/6225)
2. [https://github.com/go-gorm/mysql/pull/114](https://github.com/go-gorm/mysql/pull/114)
3. [https://github.com/go-gorm/gen/pull/822](https://github.com/go-gorm/gen/pull/822)

### User Case Description

```sql
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '姓名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';
```

image

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @maiqingqiang 

Why do you need the `TableComment` method here? can you give more information

**Comment by maiqingqiang** [comment]
> Hi @maiqingqiang
> 
> Why do you need the `TableComment` method here? can you give more information

I was inspired by this https://github.com/go-gorm/gen/issues/713. Therefore, I believe that AutoMigrate should also generate table comments.

**Comment by jinzhu** [comment]
Maybe we could merge current pr after GORM auto migrate supported this?

**Comment by maiqingqiang** [comment]
> Maybe we could merge current pr after GORM auto migrate supported this?

Alternatively, I could remove the TableComment function from this pull request and submit a new one in the future.

**Comment by jinzhu** [comment]
Going to close this PR for now, maybe we could support this after gorm itself support auto migrate table comments.

**Pull request closed without merging**
